name: Test for python_test_example
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install Library
      run: |
        python3 -m pip install --upgrade pip
        pip install requests flask
        pip install mypy==0.782
    - name: Run mypy
      run: |
        mypy python_test_example --config-file python_test_example/mypy.ini
    - name: Run unittest
      run: |
        cd python_test_example
        python3 -m unittest discover --verbose --pattern "*_test.py"
