name: Test for python_test_example
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install Library
      run: |
        python3 -m pip install --upgrade pip
        pip install requests flask mypy
    - name: Run unittest
      run: |
        cd python_test_example
        python3 -m unittest discover --verbose --pattern "*_test.py"
    - name: Run mypy
      run: |
        mypy .
